"""Generate paper_numbers.tex with measured values from analysis.json.

The output is a complete drop-in replacement: every macro has a value (either
the measured one, or the placeholder \\TBD).  paper.tex \\input{paper_numbers}
once and uses \\NCwoneeighteen, \\Betawoneeighteen etc. throughout.

Usage:
    python render_paper_numbers.py \\
        --analysis-mod47   figures_v2/mod47/analysis.json \\
        --analysis-mod31   figures_v2/mod31/analysis.json \\
        --analysis-mod59   figures_v2/mod59/analysis.json \\
        --supplemental-v1  experiments/results/v1_supplemental.json \\
        --extended-dir     experiments/results_v2/extended_inc \\
        --out              paper_numbers.tex
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

SPELLED = {32: "thirtytwo", 48: "fortyeight", 64: "sixtyfour",
           96: "ninetysix", 128: "oneeighteen", 31: "thirtyone",
           59: "fiftynine"}


def macro_name_w(w: int) -> str:
    return SPELLED.get(w, f"w{w}")


def load_or_empty(path: str | None) -> dict:
    if path and Path(path).exists():
        return json.loads(Path(path).read_text())
    return {}


def fmt(x: float | None, digits: int = 3, default: str = "\\TBD") -> str:
    if x is None:
        return default
    if abs(x) < 0.001 or abs(x) > 1e4:
        return f"{x:.2e}"
    return f"{x:.{digits}f}"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--analysis-mod47", default=None)
    ap.add_argument("--analysis-mod31", default=None)
    ap.add_argument("--analysis-mod59", default=None)
    ap.add_argument("--supplemental-v1", default=None)
    ap.add_argument("--extended-dir", default=None)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    A47 = load_or_empty(args.analysis_mod47)
    A31 = load_or_empty(args.analysis_mod31)
    A59 = load_or_empty(args.analysis_mod59)
    V1 = load_or_empty(args.supplemental_v1)

    out_lines = [
        "% Auto-generated paper_numbers.tex",
        "% Regenerated by deliverables/code/render_paper_numbers.py",
        "% Every macro is defined; \\TBD signals 'not yet measured'.",
        "",
        "\\providecommand{\\TBD}{\\textit{TBD}}",
        "",
    ]

    # ---- F3 from mod47 (preferred) or v1 (skipped: no S(t) in v1) ---------
    f3 = A47.get("f3_correlations", {})
    name_map = [
        ("S_W_out", "FthreeSWoutR"),
        ("S_W_in_a", "FthreeSWinaR"),
        ("S_W_in_b", "FthreeSWinbR"),
        ("S_H_class", "FthreeSHclassR"),
    ]
    out_lines.append("% F3 Pearson r values (prefer cross-condition correlation)")
    valid = []
    for metric, mac in name_map:
        v = f3.get(metric, {})
        # Prefer cross-condition correlation (correct F3 measure)
        r_cc = v.get("r_cross_cond")
        r_pp = v.get("r_midpoint")
        r = r_cc if r_cc is not None else r_pp
        out_lines.append(f"\\providecommand{{\\{mac}}}{{{fmt(r)}}}")
        if r is not None:
            valid.append((metric, r, v))
    # Macro yields math content WITHOUT delimiters; usages in paper wrap in $...$
    metric_display = {
        "S_W_out": "S(W_{\\text{out}})",
        "S_W_in_a": "S(W_{\\text{in}}^a)",
        "S_W_in_b": "S(W_{\\text{in}}^b)",
        "S_H_class": "S(H_{\\text{class}})",
    }
    if valid:
        best = max(valid, key=lambda kv: abs(kv[1]))
        display = metric_display.get(best[0], f"S({best[0]})")
        out_lines.append(f"\\providecommand{{\\Fthreebestmetric}}{{{display}}}")
        out_lines.append(f"\\providecommand{{\\Fthreebestr}}{{{fmt(best[1])}}}")
        out_lines.append(f"\\providecommand{{\\Fthreebestn}}{{{best[2].get('n_midpoint', 0)}}}")
    else:
        out_lines.append("\\providecommand{\\Fthreebestmetric}{\\TBD}")
        out_lines.append("\\providecommand{\\Fthreebestr}{\\TBD}")
        out_lines.append("\\providecommand{\\Fthreebestn}{\\TBD}")
    out_lines.append("")

    # ---- n_eff(t) alignment from mod47 ------------------------------------
    out_lines.append("% n_eff(t) alignment")
    n_eff = A47.get("n_eff_alignment", {})
    out_lines.append(f"\\providecommand{{\\NEffR}}{{{fmt(n_eff.get('r'))}}}")
    p_val = n_eff.get("p")
    out_lines.append(f"\\providecommand{{\\NEffP}}{{{fmt(p_val)}}}")
    n_val = n_eff.get('n')
    n_str = str(n_val) if n_val is not None else "\\TBD"
    out_lines.append(f"\\providecommand{{\\NEffN}}{{{n_str}}}")
    median = n_eff.get("median_alignment_error")
    median_str = f"{median:.0f}" if median is not None else "\\TBD"
    out_lines.append(f"\\providecommand{{\\NEffMedAlign}}{{{median_str}\\,steps}}")
    out_lines.append("")

    # ---- n_c per width: merge mod47 v2 (preferred) with v1 fallback -----
    nc_source = dict(V1.get("n_c") or {})  # start with v1 defaults
    for w_str, v in (A47.get("n_c_per_width") or {}).items():
        if v.get("n_c") is not None:
            nc_source[w_str] = v
    out_lines.append("% n_c per width (canonical mod47)")
    for w_str, v in nc_source.items():
        try:
            w = int(w_str)
        except (TypeError, ValueError):
            continue
        suffix = macro_name_w(w)
        nc = v.get("n_c")
        nc_str = str(nc) if nc else "\\TBD"
        out_lines.append(f"\\providecommand{{\\NCw{suffix}}}{{{nc_str}}}")
    out_lines.append("")

    # ---- F_eff(w) spectral ------------------------------------------------
    sp = A47.get("spectral_F_eff", {})
    out_lines.append("% F_eff(w) spectral fit")
    out_lines.append(f"\\providecommand{{\\Gammafit}}{{{fmt(sp.get('gamma'))}}}")
    out_lines.append(f"\\providecommand{{\\GammafitRsq}}{{{fmt(sp.get('r_squared'))}}}")
    out_lines.append("")

    # ---- beta per width: merge mod47 (if better fit) with v1 fallback --
    beta_source = dict(V1.get("beta") or {})
    for w_str, v in (A47.get("beta_per_width") or {}).items():
        if v.get("beta") is None:
            continue
        # Prefer A47 only if it has a better R² and at least 4 points
        n47 = v.get("n_points", 0)
        rsq47 = v.get("r_squared") or 0
        existing = beta_source.get(w_str, {})
        rsq_old = existing.get("r_squared") or 0
        if n47 >= 4 and rsq47 > rsq_old:
            beta_source[w_str] = v
    out_lines.append("% beta per width")
    for w_str, v in beta_source.items():
        try:
            w = int(w_str)
        except (TypeError, ValueError):
            continue
        suffix = macro_name_w(w)
        out_lines.append(f"\\providecommand{{\\Betaw{suffix}}}{{{fmt(v.get('beta'), digits=2)}}}")
        out_lines.append(f"\\providecommand{{\\Betaw{suffix}Stderr}}{{{fmt(v.get('stderr'), digits=2)}}}")
        out_lines.append(f"\\providecommand{{\\Betaw{suffix}Rsq}}{{{fmt(v.get('r_squared'), digits=2)}}}")
    out_lines.append("")

    # ---- F1 smoothness ratios from v1 supplemental -----------------------
    f1 = V1.get("f1") or {}
    out_lines.append("% F1 (Schaeffer smoothness) ratios")
    for w_str, v in f1.items():
        try:
            w = int(w_str)
        except (TypeError, ValueError):
            continue
        suffix = macro_name_w(w)
        out_lines.append(
            f"\\providecommand{{\\Fonew{suffix}Ratio}}{{{fmt(v.get('ratio'), digits=1)}}}")
    out_lines.append("")

    # ---- Extended training counts ---------------------------------------
    ext_dir = Path(args.extended_dir) if args.extended_dir else None
    if ext_dir and ext_dir.exists():
        ext_runs = sorted(ext_dir.glob("run_*.json"))
        ext_total = len(ext_runs)
        ext_grok = 0
        for f in ext_runs:
            r = json.loads(f.read_text())
            if r.get("grokked"):
                ext_grok += 1
        out_lines.append(f"\\providecommand{{\\ExtendedRunsTotal}}{{{ext_total}}}")
        out_lines.append(f"\\providecommand{{\\ExtendedRunsGrokked}}{{{ext_grok}}}")
    else:
        out_lines.append("\\providecommand{\\ExtendedRunsTotal}{\\TBD}")
        out_lines.append("\\providecommand{\\ExtendedRunsGrokked}{\\TBD}")
    out_lines.append("")

    # ---- Multi-task summaries -------------------------------------------
    out_lines.append("% Multi-task validation")
    for tag, A in (("modthirtyone", A31), ("modfiftynine", A59)):
        nc = A.get("n_c_per_width", {})
        if nc:
            widths = sorted(int(k) for k in nc.keys() if k.isdigit())
            if widths:
                first_nc = nc[str(widths[0])].get("n_c")
                last_nc = nc[str(widths[-1])].get("n_c")
                if first_nc and last_nc:
                    direction = "decrease" if last_nc < first_nc else "increase"
                    out_lines.append(f"\\providecommand{{\\Multitask{tag}Direction}}{{{direction}}}")
                    out_lines.append(f"\\providecommand{{\\Multitask{tag}NCfirst}}{{{first_nc}}}")
                    out_lines.append(f"\\providecommand{{\\Multitask{tag}NClast}}{{{last_nc}}}")
                    continue
        out_lines.append(f"\\providecommand{{\\Multitask{tag}Direction}}{{\\TBD}}")
        out_lines.append(f"\\providecommand{{\\Multitask{tag}NCfirst}}{{\\TBD}}")
        out_lines.append(f"\\providecommand{{\\Multitask{tag}NClast}}{{\\TBD}}")
    out_lines.append("")

    # ---- Run summary ----------------------------------------------------
    total = A47.get("total_runs", 120)
    grokked = A47.get("grokked_runs", 69)
    out_lines.append(f"\\providecommand{{\\TotalRuns}}{{{total}}}")
    out_lines.append(f"\\providecommand{{\\GrokkedRuns}}{{{grokked}}}")

    Path(args.out).write_text("\n".join(out_lines))
    print(f"Wrote {args.out}: {len(out_lines)} lines")


if __name__ == "__main__":
    main()
